import type { NextPage } from "next";
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";
import NavBar from "../components/NavBar";
import { auth } from "../firebase/firebase";


const Home: NextPage = () => {
  const [user] = useAuthState(auth);
  return (
    <div>
      <Head>
        <title>nextjs-typescript-tailwindcss-firebase boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.jonchristie.net/favicon.png"
        />
      </Head>
      <NavBar />
    </div>
  );
};

export default Home;
